In [2]:
import pandas as pd
df1 = pd.read_csv('newdat/games_extended.csv')

In [3]:

path = './nba_data'
teams = pd.read_csv(path + '/teams.csv')

In [33]:
from math import sin,asin, cos, sqrt, atan2, radians,pi
def distance(lat1, lon1, lat2, lon2):
    p = pi/180
    a = 0.5 - cos((lat2-lat1)*p)/2 + cos(lat1*p) * cos(lat2*p) * (1-cos((lon2-lon1)*p))/2
    return 12742 * asin(sqrt(a)) #2*R*asin...

In [12]:
teams.drop(["LEAGUE_ID", "MIN_YEAR", "MAX_YEAR", "ABBREVIATION", "YEARFOUNDED", "CITY", "ARENA", "ARENACAPACITY", "OWNER", "GENERALMANAGER", "DLEAGUEAFFILIATION","HEADCOACH"], axis = 1, inplace = True)

In [14]:
merged1 = pd.merge(df1, teams, left_on = "TEAM_ID_home", right_on='TEAM_ID', how='left')

In [17]:
merged1.drop(["TEAM_ID","NICKNAME"],axis = 1,inplace = True)
merged1.rename(columns={"longitude": "longi_HOME", "latitude": "lati_HOME"}, inplace = True)

In [19]:
merged2 = pd.merge(merged1, teams, left_on = "TEAM_ID_away", right_on='TEAM_ID', how='left')
merged2.drop(["TEAM_ID","NICKNAME"],axis = 1,inplace = True)
merged2.rename(columns={"longitude": "longi_AWAY", "latitude": "lati_AWAY"}, inplace = True)

In [20]:
merged2

,GAME_DATE_EST,GAME_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,REB_home,...,FT_PCT_away_cur_season,FG3_PCT_away_cur_season,AST_away_cur_season,REB_away_cur_season,WINRATE_away_cur_season,PTS_LOST_away_cur_season,longi_HOME,lati_HOME,longi_AWAY,lati_AWAY
0,3/12/2022,22101005,2021,1610612748,104.0,0.398,0.760,0.333,23.0,53.0,...,0.773792,0.350569,25.652778,44.763889,0.569444,111.527778,-80.188056,25.781389,-93.276111,44.979444
1,3/12/2022,22101006,2021,1610612741,101.0,0.443,0.933,0.429,20.0,46.0,...,0.760732,0.348465,25.084507,44.577465,0.563380,103.915493,-87.674167,41.880556,-81.688056,41.496389
2,3/12/2022,22101007,2021,1610612759,108.0,0.412,0.813,0.324,28.0,52.0,...,0.757324,0.337549,24.788732,44.873239,0.338028,112.661972,-98.437500,29.426944,-86.155556,39.763889
3,3/12/2022,22101008,2021,1610612744,122.0,0.484,0.933,0.400,33.0,55.0,...,0.771111,0.367389,23.541667,46.819444,0.597222,110.527778,-122.203056,37.750278,-87.916944,43.043611
4,3/12/2022,22101009,2021,1610612743,115.0,0.551,0.750,0.407,32.0,39.0,...,0.754423,0.354887,22.056338,45.042254,0.549296,107.408451,-105.007500,39.748611,-79.379167,43.643333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24406,10/22/2004,10400071,2004,1610612765,100.0,0.549,0.810,0.500,24.0,34.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-83.245556,42.696944,-77.020833,38.898056
24407,10/22/2004,10400068,2004,1610612738,83.0,0.431,0.706,0.273,14.0,34.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-71.062228,42.366303,-74.171111,40.733611
24408,10/22/2004,10400065,2004,1610612766,69.0,0.377,0.571,0.300,24.0,36.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-80.839167,35.225000,-122.666667,45.531667
24409,10/22/2004,10400067,2004,1610612762,103.0,0.507,0.641,0.667,25.0,43.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-111.901111,40.768333,-121.518056,38.649167
24410,10/22/2004,10400066,2004,1610612750,102.0,0.523,0.643,0.143,32.0,46.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-93.276111,44.979444,-73.993611,40.750556

In [34]:
merged2['distance_for_away'] = merged2[['longi_HOME', 'lati_HOME', 'longi_AWAY', 'lati_AWAY']].apply(lambda x: distance(x['lati_HOME'],x['longi_HOME'],  x['lati_AWAY'],x['longi_AWAY']), axis=1)

In [35]:
merged2

,GAME_DATE_EST,GAME_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,REB_home,...,FG3_PCT_away_cur_season,AST_away_cur_season,REB_away_cur_season,WINRATE_away_cur_season,PTS_LOST_away_cur_season,longi_HOME,lati_HOME,longi_AWAY,lati_AWAY,distance_for_away
0,3/12/2022,22101005,2021,1610612748,104.0,0.398,0.760,0.333,23.0,53.0,...,0.350569,25.652778,44.763889,0.569444,111.527778,-80.188056,25.781389,-93.276111,44.979444,2435.077336
1,3/12/2022,22101006,2021,1610612741,101.0,0.443,0.933,0.429,20.0,46.0,...,0.348465,25.084507,44.577465,0.563380,103.915493,-87.674167,41.880556,-81.688056,41.496389,498.799581
2,3/12/2022,22101007,2021,1610612759,108.0,0.412,0.813,0.324,28.0,52.0,...,0.337549,24.788732,44.873239,0.338028,112.661972,-98.437500,29.426944,-86.155556,39.763889,1604.712739
3,3/12/2022,22101008,2021,1610612744,122.0,0.484,0.933,0.400,33.0,55.0,...,0.367389,23.541667,46.819444,0.597222,110.527778,-122.203056,37.750278,-87.916944,43.043611,2941.106519
4,3/12/2022,22101009,2021,1610612743,115.0,0.551,0.750,0.407,32.0,39.0,...,0.354887,22.056338,45.042254,0.549296,107.408451,-105.007500,39.748611,-79.379167,43.643333,2162.351293
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24406,10/22/2004,10400071,2004,1610612765,100.0,0.549,0.810,0.500,24.0,34.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,-83.245556,42.696944,-77.020833,38.898056,672.718391
24407,10/22/2004,10400068,2004,1610612738,83.0,0.431,0.706,0.273,14.0,34.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,-71.062228,42.366303,-74.171111,40.733611,316.017150
24408,10/22/2004,10400065,2004,1610612766,69.0,0.377,0.571,0.300,24.0,36.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,-80.839167,35.225000,-122.666667,45.531667,3676.909913
24409,10/22/2004,10400067,2004,1610612762,103.0,0.507,0.641,0.667,25.0,43.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,-111.901111,40.768333,-121.518056,38.649167,855.222384
24410,10/22/2004,10400066,2004,1610612750,102.0,0.523,0.643,0.143,32.0,46.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,-93.276111,44.979444,-73.993611,40.750556,1635.857213

In [38]:
merged2.to_csv('newdat/games_extended_with_dist.csv',index=False)